export const bodyStyles = ['sedan', 'SUV', 'Coupe', 'BMW', 'Akij']
export const exteriorColor = ['Black', 'White', 'Blue', 'Gray', 'Green', 'Olive']
export const countries = [
    "United Arab Emirates",
    "France",
    "United States",
    "Germany",
    "Japan",
    "Spain",
    "Qatar",
    "Canada",
    "United Kingdom",
    "Italy",
    "Netherlands",
    "Albania",
    "Indonesia",
    "Australia",
    "Portugal",
    "New Caledonia",
    "Cayman Islands",
    "New Zealand",
    "Bahrain",
    "Monaco",
    "Austria",
    "Luxembourg",
    "Saudi Arabia",
    "Sweden",
    "Kuwait",
    "Belgium",
    "Slovenia",
    "Hungary",
    "South Africa",
    "Israel",
    "Türkiye",
    "Greece",
    "Azerbaijan"
]